USE [master]
GO

/****** Object:  Database [DBPostEngine]    Script Date: 21/11/2018 02:09:28 ******/
CREATE DATABASE [DBPostEngine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBPostEngine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEVSQLSERVER\MSSQL\DATA\DBPostEngine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBPostEngine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEVSQLSERVER\MSSQL\DATA\DBPostEngine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [DBPostEngine] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBPostEngine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBPostEngine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBPostEngine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBPostEngine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBPostEngine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBPostEngine] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBPostEngine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBPostEngine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBPostEngine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBPostEngine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBPostEngine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBPostEngine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBPostEngine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBPostEngine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBPostEngine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBPostEngine] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBPostEngine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBPostEngine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBPostEngine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBPostEngine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBPostEngine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBPostEngine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBPostEngine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBPostEngine] SET RECOVERY FULL 
GO

ALTER DATABASE [DBPostEngine] SET  MULTI_USER 
GO

ALTER DATABASE [DBPostEngine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBPostEngine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBPostEngine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBPostEngine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBPostEngine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBPostEngine] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBPostEngine] SET  READ_WRITE 
GO

